include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # === READABILITY / CONSISTENCY ===
    always_declare_return_types: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_dynamic_calls: true
    avoid_redundant_argument_values: true
    cancel_subscriptions: true
    cascade_invocations: false
    lines_longer_than_80_chars: false   # keep flexibility for widget trees
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_key_in_widget_constructors: true

    # === SAFETY / CORRECTNESS ===
    always_put_required_named_parameters_first: true
    avoid_returning_null_for_void: true
    diagnostic_describe_all_properties: true
    no_leading_underscores_for_local_identifiers: true
    package_api_docs: false
    public_member_api_docs: false
    unnecessary_late: true
    unnecessary_nullable_for_final_variable_declarations: true

    # === STYLE NITS (gentle) ===
    prefer_single_quotes: true
    use_super_parameters: true